title: Sync'd Study
description: Profiles, Projects, and Interests for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-minimal
# github:
#  is_project_page: true
#  repository_url: https://github.com/syncdstudy/syncdstudy.github.io

# GitHub Links
- [View the Sync'd Study GitHub Organization](https://github.com/syncdstudy)
- [View the Sync'd Study GitHub Pages Site](https://syncdstudy.github.io)
gems:
  - jekyll-mentions